import { createSlice } from "@reduxjs/toolkit";

// Define initial state
const initialState = {
  token: "",
  userData: {},
  constantData: {},
};

// Create a slice with reducers
export const vIP = createSlice({
  name: "vip",
  initialState,
  reducers: {
    // Update the correct field to 'token'
    setToken: (state, action) => {
      state.token = action.payload.token;
    },
    setUserData: (state, action) => {
      state.userData = action.payload;
    },
    setConstants: (state, action) => {
      state.constantData = action.payload;
    },
    resetvIPData: () => initialState,
  },
});

// Export actions from the slice
export const { setToken, setUserData, setConstants, resetvIPData } =
  vIP.actions;

// Export the reducer generated by createSlice
export default vIP.reducer;
